"""Initial migration

Revision ID: aebcd7adf3e1
Revises:
Create Date: 2025-06-02 23:07:29.966644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aebcd7adf3e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_bans')
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint('chat_ibfk_1', type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('name')
        batch_op.drop_column('group_image')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_reported')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reported', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('chat_ibfk_1', 'user', ['creator_id'], ['id'])

    op.create_table('chat_bans',
    sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='chat_bans_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_bans_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

